### ISSUE TITLE
Adding support for more cameras

### ISSUE THREAD

**Issue by winternet-studio** [isontheline/panasonic-html-image-app#1]
Awesome project! I would absolutely love to have it support my HC-V800 camera - but I don't have the tools for doing a network capture - and I guess that is the only way to figure it out, right?

**Comment by isontheline** [comment]
Hi @winternet-studio,

This repository is a fork of :
https://github.com/auberginehill/panasonic-html-image-app
https://github.com/peci1/lumix-link-desktop

Please open an issue on one of them.

I have tested the project on Lumix FZ-82 and it works great.

Best
